required = [
	"github.com/getlantern/deepcopy",
	"github.com/sirupsen/logrus",

	"k8s.io/test-infra/prow/apis/prowjobs/v1",
	"k8s.io/test-infra/prow/client/clientset/versioned",
	"k8s.io/test-infra/prow/client/clientset/versioned/typed/prowjobs/v1",
	"k8s.io/test-infra/prow/config",
	"k8s.io/test-infra/prow/pjutil",

	"k8s.io/client-go/rest",
	"k8s.io/client-go/tools/clientcmd",
	"k8s.io/client-go/kubernetes/typed/core/v1",

	"k8s.io/api/core/v1",
	"k8s.io/apimachinery/pkg/apis/meta/v1"
]

[prune]
  go-tests = true
  unused-packages = true
