required = [
	"github.com/getlantern/deepcopy",
	"github.com/sirupsen/logrus",

	"k8s.io/test-infra/prow/apis/prowjobs/v1",
	"k8s.io/test-infra/prow/client/clientset/versioned",
	"k8s.io/test-infra/prow/config",
	"k8s.io/test-infra/prow/flagutil",
	"k8s.io/test-infra/prow/github",
	"k8s.io/test-infra/prow/pjutil",

	"k8s.io/client-go/rest",
	"k8s.io/client-go/tools/clientcmd",
]

[prune]
  go-tests = true
  unused-packages = true
