required = [
	"github.com/sirupsen/logrus",
  "github.com/getlantern/deepcopy",

  "k8s.io/test-infra/prow/config",
	"k8s.io/test-infra/prow/flagutil",
  "k8s.io/test-infra/prow/github",
	"k8s.io/test-infra/prow/kube",
  "k8s.io/test-infra/prow/plugins/trigger",

  "k8s.io/apimachinery/pkg/api/equality",
  "k8s.io/apimachinery/pkg/util/diff",
]

[prune]
  go-tests = true
  unused-packages = true
